version: '0.1'

services:
  django:
    container_name: django
    build:
      context: ./gru
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./gru/:/app/
    env_file:
      - ./gru/.env
    depends_on:
      - postgresdb

  postgresdb:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - ./gru/.env