# Generated by Django 4.0 on 2023-11-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_contactleads_agent_id_contactleads_run_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactleads",
            name="superagi_run_complete",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
