# Generated by Django 4.0 on 2023-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_contactleads_superagi_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactleads",
            name="email_sent",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
